# Generated by Django 3.2.8 on 2021-10-31 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serWebsite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='audioclip',
            name='emotion',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
