# Generated by Django 3.2.8 on 2021-11-01 04:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('serWebsite', '0002_audioclip_emotion'),
    ]

    operations = [
        migrations.AddField(
            model_name='audioclip',
            name='day',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='audioclip',
            name='dd',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='audioclip',
            name='hour',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='audioclip',
            name='minute',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='audioclip',
            name='month',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='audioclip',
            name='real_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='audioclip',
            name='yyyy',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
